SET DEFINE ON
-- Usage: @setup_otc_app.sql <OTC_APP_PASSWORD>
-- Creates or adjusts the OTC_APP schema with necessary grants. Idempotent.
DEFINE OTC_APP_PWD = '&1'
WHENEVER SQLERROR CONTINUE

-- Create user if not exists; continue on error if it already exists
CREATE USER OTC_APP IDENTIFIED BY "&OTC_APP_PWD" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;

-- Ensure user properties (idempotent)
ALTER USER OTC_APP DEFAULT TABLESPACE USERS;
ALTER USER OTC_APP TEMPORARY TABLESPACE TEMP;
ALTER USER OTC_APP QUOTA UNLIMITED ON USERS;

-- Minimal grants for development (avoid RESOURCE role; grant explicit privileges)
GRANT CREATE SESSION TO OTC_APP;
GRANT CREATE TABLE TO OTC_APP;
GRANT CREATE VIEW TO OTC_APP;
GRANT CREATE SEQUENCE TO OTC_APP;
GRANT CREATE PROCEDURE TO OTC_APP;
GRANT CREATE TRIGGER TO OTC_APP;
GRANT CREATE TYPE TO OTC_APP;

-- Optional: allow synonyms if needed
GRANT CREATE SYNONYM TO OTC_APP;

PROMPT OTC_APP schema ensured.